name: Exemplo-GitActions

on: 
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v3.14.5
      env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
